server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        #  使用 githu 外部配置
        git:
          #git@github.com:feifeidengni/springcloud-config.git         #ssh的路径
          uri: https://github.com/feifeidengni/springcloud-config.git #填写你自己的github路径
          search-paths:
            - springcloud-config
      label: master
   #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka
#rabbitmq 相关配置，暴露bus刷新配置的端点。
management:
  endpoints:   #暴露bus刷新配置的端点
    web:
      exposure:
        include: "bus-refresh"

